# Use the official Python image
FROM mcr.microsoft.com/devcontainers/python:3.11

# Install dependencies
RUN pip install --upgrade pip

# Create a working directory
WORKDIR /workspace

# Default shell
SHELL ["/bin/bash", "-c"]
